mysql:
  container_name: mysql
  image: mysql:latest
  ports:
    - "3306:3306"
  environment:
    - "MYSQL_ROOT_PASSWORD=password"
    - "MYSQL_DATABASE=test"
  volumes:
    - ./install.sql:/docker-entrypoint-initdb.d/install.sql
  restart: always

